### ISSUE TITLE
the runtime error

### ISSUE THREAD

**Issue by weiningwei** [symao/PnPL#7]
Hi, @symao . Thanks for sharing the code.
I can run this ./demo_pnptrans succeefully. But when I run ./demo_pnpl, it have an error "Segmentation fault (core dumped)"

**Comment by ElonKou** [comment]
> Hi, @symao . Thanks for sharing the code.
> I can run this ./demo_pnptrans succeefully. But when I run ./demo_pnpl, it have an error "Segmentation fault (core dumped)"

Hi, did you solved the question, I met the same question, could you please tell me how to fix this problem? thank you!

**Comment by weiningwei** [comment]
Hi, I remember it should be the problem of g2o version. You can change the version to [https://github.com/RainerKuemmerle/g2o/tree/20160424_git](url).

**Comment by ElonKou** [comment]
> Hi, I remember it should be the problem of g2o version. You can change the version to [https://github.com/RainerKuemmerle/g2o/tree/20160424_git](url).

Thank you very much, I solved the question by using `ros-kinetic-libg2o`(20160424) package.
